# Generated by Django 3.1.2 on 2020-11-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['owner', 'name']},
        ),
    ]
