# Generated by Django 3.1.2 on 2020-11-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='core.Profile'),
        ),
    ]
