# Generated by Django 3.1.2 on 2020-11-26 18:20

import EOH.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('initialized', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=EOH.models.Performance.columns_default, size=None)),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('initialized', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOH.node')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performance',
            },
        ),
    ]
