# Generated by Django 3.1.2 on 2020-12-03 18:55

import EOH.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('initialized', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=EOH.models.Performance.general_default, size=None)),
                ('general_data', models.FileField(upload_to='performance/%Y/%m/general')),
                ('cpu_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=EOH.models.Performance.gpu_default, size=None)),
                ('cpu_data', models.FileField(upload_to='performance/%Y/%m/cpu')),
                ('gpu_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=EOH.models.Performance.cpu_default, size=None)),
                ('gpu_data', models.FileField(upload_to='performance/%Y/%m/gpu')),
                ('data_start', models.DateTimeField(blank=True, null=True)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('rows', models.IntegerField(default=0)),
                ('initialized', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOH.node')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performance',
            },
        ),
    ]
