# Generated by Django 3.1.2 on 2020-11-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOH', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['node', 'data_start', 'data_end'], 'verbose_name': 'Performance', 'verbose_name_plural': 'Performance'},
        ),
    ]
