# Generated by Django 3.1.2 on 2020-12-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EOH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='initialized',
            new_name='created',
        ),
    ]
